sample_transactions = [
    {
        "transaction_id": "TXN1001",
        "account_id": "ACC5001",
        "merchant": "Amazon",
        "merchant_category": "Retail",
        "amount": 124.99,
        "transaction_type": "debit_card",
        "location": "Philadelphia, PA",
    },
    {
        "transaction_id": "TXN1002",
        "account_id": "ACC5002",
        "merchant": "Shell",
        "merchant_category": "Gas",
        "amount": 48.27,
        "transaction_type": "debit_card",
        "location": "Wilmington, DE",
    },
    {
        "transaction_id": "TXN1003",
        "account_id": "ACC5003",
        "merchant": "Best Buy",
        "merchant_category": "Electronics",
        "amount": 1299.99,
        "transaction_type": "credit_card",
        "location": "Newark, DE",
    },
    {
        "transaction_id": "TXN1004",
        "account_id": "ACC5001",
        "merchant": "Uber",
        "merchant_category": "Travel",
        "amount": 19.55,
        "transaction_type": "credit_card",
        "location": "Philadelphia, PA",
    },
    {
        "transaction_id": "TXN1005",
        "account_id": "ACC5004",
        "merchant": "ATM Withdrawal",
        "merchant_category": "Cash",
        "amount": 500.00,
        "transaction_type": "atm",
        "location": "Baltimore, MD",
    },
    {
        "transaction_id": "TXN1006",
        "account_id": "ACC5005",
        "merchant": "International Wire",
        "merchant_category": "Transfer",
        "amount": 6200.00,
        "transaction_type": "wire",
        "location": "London, UK",
    },
]